cxx_binary(
    name = 'test',
    srcs = glob([
        'test.cpp',
    ]),
    deps = [
        '//yazik:yazik',
        '//third-party:boost-context',
        '//third-party:boost-common',
    ],
)
