cxx_binary(
    name = 'test',
    srcs = glob([
        'test.cpp',
    ]),
    deps = [
        '//yazik:yazik',
    ],
)


apple_library(
    name = 'testapple',
    deps = [
        '//yazik:yazik',
    ],
    preprocessor_flags = ['-fobjc-arc'],
    srcs = [
        'testapple.mm',
    ],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    ],
)
