includeDir = 'include'
srcDir = 'src'

cxx_library(
    name = 'yazik',
    exported_headers = subdir_glob([
        ( includeDir, './**/*.hpp'),
        ( includeDir, './**/*.h'),
    ]),
    srcs = glob([
        srcDir + "./**/*.cpp"
    ]),
    visibility = ['PUBLIC',],
    header_namespace = 'yazik',
    deps = [
        '//third-party:boost-context',
        '//third-party:boost-common',
        '//third-party:ltalloc',
    ],
)
